
namespace Umoxi
{
    partial class frmAddBus
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAddBus));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.NavigationBar = new DevExpress.XtraBars.Navigation.OfficeNavigationBar();
            this.tabInfo = new DevExpress.XtraBars.Navigation.NavigationBarItem();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.txtBusID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSupervisorContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblSupervisorContact = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtSupervisorName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblSupervisorName = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtDriverContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDriverContact = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtDriverName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDriverName = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtBusNO = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblBusNO = new Bunifu.UI.WinForms.BunifuLabel();
            this.transitionManager = new DevExpress.Utils.Animation.TransitionManager(this.components);
            this.Snackbar = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.NavigationBar)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.btnSave);
            this.panel1.Controls.Add(this.btnClose);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 384);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(334, 57);
            this.panel1.TabIndex = 116;
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges1;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Rubik", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = null;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.btnSave.IdleBorderRadius = 10;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(225, 13);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 10;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(176)))), ((int)(((byte)(218)))));
            this.btnSave.onHoverState.BorderRadius = 10;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(176)))), ((int)(((byte)(218)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.btnSave.OnIdleState.BorderRadius = 10;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(62)))), ((int)(((byte)(103)))));
            this.btnSave.OnPressedState.BorderRadius = 10;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(62)))), ((int)(((byte)(103)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(97, 32);
            this.btnSave.TabIndex = 77;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.White;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Close";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges2;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Rubik", 9F);
            this.btnClose.ForeColor = System.Drawing.Color.Gray;
            this.btnClose.IconLeft = null;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRight = null;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.Silver;
            this.btnClose.IdleBorderRadius = 10;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.White;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(122, 13);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 10;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnClose.onHoverState.BorderRadius = 10;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(200)))), ((int)(((byte)(207)))));
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.btnClose.OnIdleState.BorderRadius = 10;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(189)))), ((int)(((byte)(198)))));
            this.btnClose.OnPressedState.BorderRadius = 10;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(189)))), ((int)(((byte)(198)))));
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(97, 32);
            this.btnClose.TabIndex = 78;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // NavigationBar
            // 
            this.NavigationBar.AppearanceItem.Disabled.Font = new System.Drawing.Font("Rubik", 12F);
            this.NavigationBar.AppearanceItem.Disabled.Options.UseFont = true;
            this.NavigationBar.AppearanceItem.Hovered.Font = new System.Drawing.Font("Rubik", 12F);
            this.NavigationBar.AppearanceItem.Hovered.Options.UseFont = true;
            this.NavigationBar.AppearanceItem.Normal.Font = new System.Drawing.Font("Rubik", 12F);
            this.NavigationBar.AppearanceItem.Normal.Options.UseFont = true;
            this.NavigationBar.AppearanceItem.Pressed.Font = new System.Drawing.Font("Rubik", 12F);
            this.NavigationBar.AppearanceItem.Pressed.Options.UseFont = true;
            this.NavigationBar.AppearanceItem.Selected.Font = new System.Drawing.Font("Rubik", 12F);
            this.NavigationBar.AppearanceItem.Selected.Options.UseFont = true;
            this.NavigationBar.AutoSize = false;
            this.NavigationBar.BackColor = System.Drawing.Color.Transparent;
            this.NavigationBar.CustomizationButtonVisibility = DevExpress.XtraBars.Navigation.CustomizationButtonVisibility.Hidden;
            this.NavigationBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.NavigationBar.Font = new System.Drawing.Font("Rubik", 5.25F);
            this.NavigationBar.Items.AddRange(new DevExpress.XtraBars.Navigation.NavigationBarItem[] {
            this.tabInfo});
            this.NavigationBar.Location = new System.Drawing.Point(0, 0);
            this.NavigationBar.LookAndFeel.SkinName = "Office 2019 White";
            this.NavigationBar.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
            this.NavigationBar.LookAndFeel.UseDefaultLookAndFeel = false;
            this.NavigationBar.Name = "NavigationBar";
            this.NavigationBar.SelectedItem = this.tabInfo;
            this.NavigationBar.Size = new System.Drawing.Size(334, 30);
            this.NavigationBar.TabIndex = 117;
            this.NavigationBar.Text = "NavigationBar1";
            this.NavigationBar.ViewMode = DevExpress.XtraBars.Navigation.OfficeNavigationBarViewMode.Tab;
            // 
            // tabInfo
            // 
            this.tabInfo.Name = "tabInfo";
            this.tabInfo.Text = "Bus";
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(244)))), ((int)(((byte)(245)))));
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(0, 383);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(334, 1);
            this.bunifuSeparator2.TabIndex = 131;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(244)))), ((int)(((byte)(245)))));
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(0, 30);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(334, 1);
            this.bunifuSeparator1.TabIndex = 132;
            // 
            // txtBusID
            // 
            this.txtBusID.AcceptsReturn = false;
            this.txtBusID.AcceptsTab = false;
            this.txtBusID.AnimationSpeed = 200;
            this.txtBusID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBusID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBusID.AutoSizeHeight = true;
            this.txtBusID.BackColor = System.Drawing.Color.White;
            this.txtBusID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBusID.BackgroundImage")));
            this.txtBusID.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtBusID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBusID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBusID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBusID.BorderRadius = 10;
            this.txtBusID.BorderThickness = 1;
            this.txtBusID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBusID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusID.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtBusID.DefaultText = "";
            this.txtBusID.FillColor = System.Drawing.Color.White;
            this.txtBusID.HideSelection = true;
            this.txtBusID.IconLeft = null;
            this.txtBusID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusID.IconPadding = 10;
            this.txtBusID.IconRight = null;
            this.txtBusID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusID.Lines = new string[0];
            this.txtBusID.Location = new System.Drawing.Point(0, 64);
            this.txtBusID.MaxLength = 32767;
            this.txtBusID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBusID.Modified = false;
            this.txtBusID.Multiline = false;
            this.txtBusID.Name = "txtBusID";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBusID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusID.OnIdleState = stateProperties4;
            this.txtBusID.Padding = new System.Windows.Forms.Padding(3);
            this.txtBusID.PasswordChar = '\0';
            this.txtBusID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBusID.PlaceholderText = "";
            this.txtBusID.ReadOnly = false;
            this.txtBusID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBusID.SelectedText = "";
            this.txtBusID.SelectionLength = 0;
            this.txtBusID.SelectionStart = 0;
            this.txtBusID.ShortcutsEnabled = true;
            this.txtBusID.Size = new System.Drawing.Size(23, 35);
            this.txtBusID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBusID.TabIndex = 145;
            this.txtBusID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBusID.TextMarginBottom = 0;
            this.txtBusID.TextMarginLeft = 3;
            this.txtBusID.TextMarginTop = 0;
            this.txtBusID.TextPlaceholder = "";
            this.txtBusID.UseSystemPasswordChar = false;
            this.txtBusID.Visible = false;
            this.txtBusID.WordWrap = true;
            // 
            // txtSupervisorContact
            // 
            this.txtSupervisorContact.AcceptsReturn = false;
            this.txtSupervisorContact.AcceptsTab = false;
            this.txtSupervisorContact.AnimationSpeed = 200;
            this.txtSupervisorContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSupervisorContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSupervisorContact.AutoSizeHeight = true;
            this.txtSupervisorContact.BackColor = System.Drawing.Color.White;
            this.txtSupervisorContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSupervisorContact.BackgroundImage")));
            this.txtSupervisorContact.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtSupervisorContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSupervisorContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSupervisorContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSupervisorContact.BorderRadius = 10;
            this.txtSupervisorContact.BorderThickness = 1;
            this.txtSupervisorContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSupervisorContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorContact.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtSupervisorContact.DefaultText = "";
            this.txtSupervisorContact.FillColor = System.Drawing.Color.White;
            this.txtSupervisorContact.HideSelection = true;
            this.txtSupervisorContact.IconLeft = null;
            this.txtSupervisorContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorContact.IconPadding = 10;
            this.txtSupervisorContact.IconRight = null;
            this.txtSupervisorContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorContact.Lines = new string[0];
            this.txtSupervisorContact.Location = new System.Drawing.Point(29, 333);
            this.txtSupervisorContact.MaxLength = 32767;
            this.txtSupervisorContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSupervisorContact.Modified = false;
            this.txtSupervisorContact.Multiline = false;
            this.txtSupervisorContact.Name = "txtSupervisorContact";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorContact.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSupervisorContact.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorContact.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorContact.OnIdleState = stateProperties8;
            this.txtSupervisorContact.Padding = new System.Windows.Forms.Padding(3);
            this.txtSupervisorContact.PasswordChar = '\0';
            this.txtSupervisorContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSupervisorContact.PlaceholderText = "";
            this.txtSupervisorContact.ReadOnly = false;
            this.txtSupervisorContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSupervisorContact.SelectedText = "";
            this.txtSupervisorContact.SelectionLength = 0;
            this.txtSupervisorContact.SelectionStart = 0;
            this.txtSupervisorContact.ShortcutsEnabled = true;
            this.txtSupervisorContact.Size = new System.Drawing.Size(270, 35);
            this.txtSupervisorContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSupervisorContact.TabIndex = 141;
            this.txtSupervisorContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSupervisorContact.TextMarginBottom = 0;
            this.txtSupervisorContact.TextMarginLeft = 3;
            this.txtSupervisorContact.TextMarginTop = 0;
            this.txtSupervisorContact.TextPlaceholder = "";
            this.txtSupervisorContact.UseSystemPasswordChar = false;
            this.txtSupervisorContact.WordWrap = true;
            // 
            // lblSupervisorContact
            // 
            this.lblSupervisorContact.AllowParentOverrides = false;
            this.lblSupervisorContact.AutoEllipsis = false;
            this.lblSupervisorContact.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblSupervisorContact.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblSupervisorContact.Font = new System.Drawing.Font("Rubik", 9F);
            this.lblSupervisorContact.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(61)))), ((int)(((byte)(61)))));
            this.lblSupervisorContact.Location = new System.Drawing.Point(33, 314);
            this.lblSupervisorContact.Name = "lblSupervisorContact";
            this.lblSupervisorContact.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSupervisorContact.Size = new System.Drawing.Size(109, 15);
            this.lblSupervisorContact.TabIndex = 142;
            this.lblSupervisorContact.Text = "Supervisor contact";
            this.lblSupervisorContact.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSupervisorContact.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtSupervisorName
            // 
            this.txtSupervisorName.AcceptsReturn = false;
            this.txtSupervisorName.AcceptsTab = false;
            this.txtSupervisorName.AnimationSpeed = 200;
            this.txtSupervisorName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSupervisorName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSupervisorName.AutoSizeHeight = true;
            this.txtSupervisorName.BackColor = System.Drawing.Color.White;
            this.txtSupervisorName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSupervisorName.BackgroundImage")));
            this.txtSupervisorName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtSupervisorName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSupervisorName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSupervisorName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSupervisorName.BorderRadius = 10;
            this.txtSupervisorName.BorderThickness = 1;
            this.txtSupervisorName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSupervisorName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorName.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtSupervisorName.DefaultText = "";
            this.txtSupervisorName.FillColor = System.Drawing.Color.White;
            this.txtSupervisorName.HideSelection = true;
            this.txtSupervisorName.IconLeft = null;
            this.txtSupervisorName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorName.IconPadding = 10;
            this.txtSupervisorName.IconRight = null;
            this.txtSupervisorName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSupervisorName.Lines = new string[0];
            this.txtSupervisorName.Location = new System.Drawing.Point(29, 264);
            this.txtSupervisorName.MaxLength = 32767;
            this.txtSupervisorName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSupervisorName.Modified = false;
            this.txtSupervisorName.Multiline = false;
            this.txtSupervisorName.Name = "txtSupervisorName";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSupervisorName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSupervisorName.OnIdleState = stateProperties12;
            this.txtSupervisorName.Padding = new System.Windows.Forms.Padding(3);
            this.txtSupervisorName.PasswordChar = '\0';
            this.txtSupervisorName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSupervisorName.PlaceholderText = "";
            this.txtSupervisorName.ReadOnly = false;
            this.txtSupervisorName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSupervisorName.SelectedText = "";
            this.txtSupervisorName.SelectionLength = 0;
            this.txtSupervisorName.SelectionStart = 0;
            this.txtSupervisorName.ShortcutsEnabled = true;
            this.txtSupervisorName.Size = new System.Drawing.Size(270, 35);
            this.txtSupervisorName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSupervisorName.TabIndex = 139;
            this.txtSupervisorName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSupervisorName.TextMarginBottom = 0;
            this.txtSupervisorName.TextMarginLeft = 3;
            this.txtSupervisorName.TextMarginTop = 0;
            this.txtSupervisorName.TextPlaceholder = "";
            this.txtSupervisorName.UseSystemPasswordChar = false;
            this.txtSupervisorName.WordWrap = true;
            // 
            // lblSupervisorName
            // 
            this.lblSupervisorName.AllowParentOverrides = false;
            this.lblSupervisorName.AutoEllipsis = false;
            this.lblSupervisorName.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblSupervisorName.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblSupervisorName.Font = new System.Drawing.Font("Rubik", 9F);
            this.lblSupervisorName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(61)))), ((int)(((byte)(61)))));
            this.lblSupervisorName.Location = new System.Drawing.Point(33, 245);
            this.lblSupervisorName.Name = "lblSupervisorName";
            this.lblSupervisorName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSupervisorName.Size = new System.Drawing.Size(61, 15);
            this.lblSupervisorName.TabIndex = 140;
            this.lblSupervisorName.Text = "Supervisor";
            this.lblSupervisorName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSupervisorName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtDriverContact
            // 
            this.txtDriverContact.AcceptsReturn = false;
            this.txtDriverContact.AcceptsTab = false;
            this.txtDriverContact.AnimationSpeed = 200;
            this.txtDriverContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDriverContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDriverContact.AutoSizeHeight = true;
            this.txtDriverContact.BackColor = System.Drawing.Color.White;
            this.txtDriverContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDriverContact.BackgroundImage")));
            this.txtDriverContact.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtDriverContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDriverContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDriverContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDriverContact.BorderRadius = 10;
            this.txtDriverContact.BorderThickness = 1;
            this.txtDriverContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDriverContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverContact.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtDriverContact.DefaultText = "";
            this.txtDriverContact.FillColor = System.Drawing.Color.White;
            this.txtDriverContact.HideSelection = true;
            this.txtDriverContact.IconLeft = null;
            this.txtDriverContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverContact.IconPadding = 10;
            this.txtDriverContact.IconRight = null;
            this.txtDriverContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverContact.Lines = new string[0];
            this.txtDriverContact.Location = new System.Drawing.Point(29, 198);
            this.txtDriverContact.MaxLength = 32767;
            this.txtDriverContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDriverContact.Modified = false;
            this.txtDriverContact.Multiline = false;
            this.txtDriverContact.Name = "txtDriverContact";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverContact.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDriverContact.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverContact.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverContact.OnIdleState = stateProperties16;
            this.txtDriverContact.Padding = new System.Windows.Forms.Padding(3);
            this.txtDriverContact.PasswordChar = '\0';
            this.txtDriverContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDriverContact.PlaceholderText = "";
            this.txtDriverContact.ReadOnly = false;
            this.txtDriverContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDriverContact.SelectedText = "";
            this.txtDriverContact.SelectionLength = 0;
            this.txtDriverContact.SelectionStart = 0;
            this.txtDriverContact.ShortcutsEnabled = true;
            this.txtDriverContact.Size = new System.Drawing.Size(270, 35);
            this.txtDriverContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDriverContact.TabIndex = 137;
            this.txtDriverContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDriverContact.TextMarginBottom = 0;
            this.txtDriverContact.TextMarginLeft = 3;
            this.txtDriverContact.TextMarginTop = 0;
            this.txtDriverContact.TextPlaceholder = "";
            this.txtDriverContact.UseSystemPasswordChar = false;
            this.txtDriverContact.WordWrap = true;
            // 
            // lblDriverContact
            // 
            this.lblDriverContact.AllowParentOverrides = false;
            this.lblDriverContact.AutoEllipsis = false;
            this.lblDriverContact.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblDriverContact.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblDriverContact.Font = new System.Drawing.Font("Rubik", 9F);
            this.lblDriverContact.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(61)))), ((int)(((byte)(61)))));
            this.lblDriverContact.Location = new System.Drawing.Point(33, 179);
            this.lblDriverContact.Name = "lblDriverContact";
            this.lblDriverContact.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDriverContact.Size = new System.Drawing.Size(46, 15);
            this.lblDriverContact.TabIndex = 138;
            this.lblDriverContact.Text = "Contact";
            this.lblDriverContact.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDriverContact.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtDriverName
            // 
            this.txtDriverName.AcceptsReturn = false;
            this.txtDriverName.AcceptsTab = false;
            this.txtDriverName.AnimationSpeed = 200;
            this.txtDriverName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDriverName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDriverName.AutoSizeHeight = true;
            this.txtDriverName.BackColor = System.Drawing.Color.White;
            this.txtDriverName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDriverName.BackgroundImage")));
            this.txtDriverName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtDriverName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDriverName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDriverName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDriverName.BorderRadius = 10;
            this.txtDriverName.BorderThickness = 1;
            this.txtDriverName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDriverName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverName.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtDriverName.DefaultText = "";
            this.txtDriverName.FillColor = System.Drawing.Color.White;
            this.txtDriverName.HideSelection = true;
            this.txtDriverName.IconLeft = null;
            this.txtDriverName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverName.IconPadding = 10;
            this.txtDriverName.IconRight = null;
            this.txtDriverName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDriverName.Lines = new string[0];
            this.txtDriverName.Location = new System.Drawing.Point(29, 129);
            this.txtDriverName.MaxLength = 32767;
            this.txtDriverName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDriverName.Modified = false;
            this.txtDriverName.Multiline = false;
            this.txtDriverName.Name = "txtDriverName";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDriverName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDriverName.OnIdleState = stateProperties20;
            this.txtDriverName.Padding = new System.Windows.Forms.Padding(3);
            this.txtDriverName.PasswordChar = '\0';
            this.txtDriverName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDriverName.PlaceholderText = "";
            this.txtDriverName.ReadOnly = false;
            this.txtDriverName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDriverName.SelectedText = "";
            this.txtDriverName.SelectionLength = 0;
            this.txtDriverName.SelectionStart = 0;
            this.txtDriverName.ShortcutsEnabled = true;
            this.txtDriverName.Size = new System.Drawing.Size(270, 35);
            this.txtDriverName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDriverName.TabIndex = 135;
            this.txtDriverName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDriverName.TextMarginBottom = 0;
            this.txtDriverName.TextMarginLeft = 3;
            this.txtDriverName.TextMarginTop = 0;
            this.txtDriverName.TextPlaceholder = "";
            this.txtDriverName.UseSystemPasswordChar = false;
            this.txtDriverName.WordWrap = true;
            // 
            // lblDriverName
            // 
            this.lblDriverName.AllowParentOverrides = false;
            this.lblDriverName.AutoEllipsis = false;
            this.lblDriverName.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblDriverName.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblDriverName.Font = new System.Drawing.Font("Rubik", 9F);
            this.lblDriverName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(61)))), ((int)(((byte)(61)))));
            this.lblDriverName.Location = new System.Drawing.Point(33, 110);
            this.lblDriverName.Name = "lblDriverName";
            this.lblDriverName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDriverName.Size = new System.Drawing.Size(78, 15);
            this.lblDriverName.TabIndex = 136;
            this.lblDriverName.Text = "Driver name  *";
            this.lblDriverName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDriverName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtBusNO
            // 
            this.txtBusNO.AcceptsReturn = false;
            this.txtBusNO.AcceptsTab = false;
            this.txtBusNO.AnimationSpeed = 200;
            this.txtBusNO.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBusNO.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBusNO.AutoSizeHeight = true;
            this.txtBusNO.BackColor = System.Drawing.Color.White;
            this.txtBusNO.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBusNO.BackgroundImage")));
            this.txtBusNO.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            this.txtBusNO.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBusNO.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtBusNO.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtBusNO.BorderRadius = 10;
            this.txtBusNO.BorderThickness = 1;
            this.txtBusNO.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBusNO.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusNO.DefaultFont = new System.Drawing.Font("Rubik", 9.25F);
            this.txtBusNO.DefaultText = "";
            this.txtBusNO.FillColor = System.Drawing.Color.White;
            this.txtBusNO.HideSelection = true;
            this.txtBusNO.IconLeft = null;
            this.txtBusNO.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusNO.IconPadding = 10;
            this.txtBusNO.IconRight = null;
            this.txtBusNO.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBusNO.Lines = new string[0];
            this.txtBusNO.Location = new System.Drawing.Point(29, 64);
            this.txtBusNO.MaxLength = 32767;
            this.txtBusNO.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBusNO.Modified = false;
            this.txtBusNO.Multiline = false;
            this.txtBusNO.Name = "txtBusNO";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(113)))), ((int)(((byte)(188)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusNO.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBusNO.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusNO.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBusNO.OnIdleState = stateProperties24;
            this.txtBusNO.Padding = new System.Windows.Forms.Padding(3);
            this.txtBusNO.PasswordChar = '\0';
            this.txtBusNO.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBusNO.PlaceholderText = "";
            this.txtBusNO.ReadOnly = false;
            this.txtBusNO.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBusNO.SelectedText = "";
            this.txtBusNO.SelectionLength = 0;
            this.txtBusNO.SelectionStart = 0;
            this.txtBusNO.ShortcutsEnabled = true;
            this.txtBusNO.Size = new System.Drawing.Size(270, 35);
            this.txtBusNO.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBusNO.TabIndex = 133;
            this.txtBusNO.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBusNO.TextMarginBottom = 0;
            this.txtBusNO.TextMarginLeft = 3;
            this.txtBusNO.TextMarginTop = 0;
            this.txtBusNO.TextPlaceholder = "";
            this.txtBusNO.UseSystemPasswordChar = false;
            this.txtBusNO.WordWrap = true;
            // 
            // lblBusNO
            // 
            this.lblBusNO.AllowParentOverrides = false;
            this.lblBusNO.AutoEllipsis = false;
            this.lblBusNO.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblBusNO.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblBusNO.Font = new System.Drawing.Font("Rubik", 9F);
            this.lblBusNO.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(61)))), ((int)(((byte)(61)))));
            this.lblBusNO.Location = new System.Drawing.Point(33, 45);
            this.lblBusNO.Name = "lblBusNO";
            this.lblBusNO.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblBusNO.Size = new System.Drawing.Size(29, 15);
            this.lblBusNO.TabIndex = 134;
            this.lblBusNO.Text = "Bus *";
            this.lblBusNO.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblBusNO.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // transitionManager
            // 
            this.transitionManager.FrameCount = 400;
            this.transitionManager.ShowWaitingIndicator = false;
            // 
            // Snackbar
            // 
            this.Snackbar.AllowDragging = false;
            this.Snackbar.AllowMultipleViews = true;
            this.Snackbar.ClickToClose = true;
            this.Snackbar.DoubleClickToClose = true;
            this.Snackbar.DurationAfterIdle = 3000;
            this.Snackbar.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Snackbar.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(74)))), ((int)(((byte)(76)))));
            this.Snackbar.ErrorOptions.ActionBorderRadius = 1;
            this.Snackbar.ErrorOptions.ActionFont = new System.Drawing.Font("Rubik", 8.25F, System.Drawing.FontStyle.Bold);
            this.Snackbar.ErrorOptions.ActionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(74)))), ((int)(((byte)(76)))));
            this.Snackbar.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Snackbar.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Snackbar.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Snackbar.ErrorOptions.Font = new System.Drawing.Font("Rubik", 9.75F);
            this.Snackbar.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Snackbar.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Snackbar.ErrorOptions.IconLeftMargin = 12;
            this.Snackbar.FadeCloseIcon = false;
            this.Snackbar.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Snackbar.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Snackbar.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(149)))), ((int)(((byte)(242)))));
            this.Snackbar.InformationOptions.ActionBorderRadius = 1;
            this.Snackbar.InformationOptions.ActionFont = new System.Drawing.Font("Rubik", 8.25F);
            this.Snackbar.InformationOptions.ActionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(149)))), ((int)(((byte)(242)))));
            this.Snackbar.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Snackbar.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Snackbar.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Snackbar.InformationOptions.Font = new System.Drawing.Font("Rubik", 9.75F);
            this.Snackbar.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Snackbar.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Snackbar.InformationOptions.IconLeftMargin = 12;
            this.Snackbar.Margin = 10;
            this.Snackbar.MaximumSize = new System.Drawing.Size(0, 0);
            this.Snackbar.MaximumViews = 7;
            this.Snackbar.MessageRightMargin = 15;
            this.Snackbar.MinimumSize = new System.Drawing.Size(0, 0);
            this.Snackbar.ShowBorders = false;
            this.Snackbar.ShowCloseIcon = true;
            this.Snackbar.ShowIcon = true;
            this.Snackbar.ShowShadows = true;
            this.Snackbar.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Snackbar.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(196)))), ((int)(((byte)(26)))));
            this.Snackbar.SuccessOptions.ActionBorderRadius = 1;
            this.Snackbar.SuccessOptions.ActionFont = new System.Drawing.Font("Rubik", 8.25F);
            this.Snackbar.SuccessOptions.ActionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(196)))), ((int)(((byte)(26)))));
            this.Snackbar.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Snackbar.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Snackbar.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Snackbar.SuccessOptions.Font = new System.Drawing.Font("Rubik", 9.75F);
            this.Snackbar.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Snackbar.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Snackbar.SuccessOptions.IconLeftMargin = 12;
            this.Snackbar.ViewsMargin = 7;
            this.Snackbar.WarningOptions.ActionBackColor = System.Drawing.Color.White;
            this.Snackbar.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(173)))), ((int)(((byte)(20)))));
            this.Snackbar.WarningOptions.ActionBorderRadius = 5;
            this.Snackbar.WarningOptions.ActionFont = new System.Drawing.Font("Rubik", 8.25F);
            this.Snackbar.WarningOptions.ActionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(173)))), ((int)(((byte)(20)))));
            this.Snackbar.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Snackbar.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Snackbar.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Snackbar.WarningOptions.Font = new System.Drawing.Font("Rubik", 9.75F);
            this.Snackbar.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Snackbar.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Snackbar.WarningOptions.IconLeftMargin = 12;
            this.Snackbar.ZoomCloseIcon = true;
            // 
            // frmAddBus
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(334, 441);
            this.Controls.Add(this.txtBusID);
            this.Controls.Add(this.txtSupervisorContact);
            this.Controls.Add(this.lblSupervisorContact);
            this.Controls.Add(this.txtSupervisorName);
            this.Controls.Add(this.lblSupervisorName);
            this.Controls.Add(this.txtDriverContact);
            this.Controls.Add(this.lblDriverContact);
            this.Controls.Add(this.txtDriverName);
            this.Controls.Add(this.lblDriverName);
            this.Controls.Add(this.txtBusNO);
            this.Controls.Add(this.lblBusNO);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.bunifuSeparator2);
            this.Controls.Add(this.NavigationBar);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmAddBus";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.frmAddBus_FormClosed);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.NavigationBar)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        internal Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
        private DevExpress.XtraBars.Navigation.OfficeNavigationBar NavigationBar;
        private DevExpress.XtraBars.Navigation.NavigationBarItem tabInfo;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        internal Bunifu.UI.WinForms.BunifuTextBox txtBusID;
        internal Bunifu.UI.WinForms.BunifuTextBox txtSupervisorContact;
        private Bunifu.UI.WinForms.BunifuLabel lblSupervisorContact;
        internal Bunifu.UI.WinForms.BunifuTextBox txtSupervisorName;
        private Bunifu.UI.WinForms.BunifuLabel lblSupervisorName;
        internal Bunifu.UI.WinForms.BunifuTextBox txtDriverContact;
        private Bunifu.UI.WinForms.BunifuLabel lblDriverContact;
        internal Bunifu.UI.WinForms.BunifuTextBox txtDriverName;
        private Bunifu.UI.WinForms.BunifuLabel lblDriverName;
        internal Bunifu.UI.WinForms.BunifuTextBox txtBusNO;
        private Bunifu.UI.WinForms.BunifuLabel lblBusNO;
        private DevExpress.Utils.Animation.TransitionManager transitionManager;
        private Bunifu.UI.WinForms.BunifuSnackbar Snackbar;
    }
}